deployment:
  name: grpc-product-service
  replicaCount: 1
  image:
    name: nrt.ocir.io/nrcmxxv7sjse/ec_service_test:stg-grpc-product-service-stg-20250708-095012
  ports:
    containerPort: 50052
    protocol: TCP
service:
  name: grpc-product-service
  ports:
    port: 50052
    targetPort: 50052
selector:
  app: grpc-product-service
