deployment:
  name: kafka-worker
  replicaCount: 2
  env:
    bootstrapServers: kafka-service:9092
  image:
    name: nrt.ocir.io/nrcmxxv7sjse/ec_service_test:main-kafka-worker-main-v1.0
service:
  name: kafka-worker
  ports:
    protocol: TCP
    port: 8080
    targetPort: 8080
selector:
  app: kafka-worker
