deployment:
  name: grpc-payment-service
  replicaCount: 1
  image:
    name: nrt.ocir.io/nrcmxxv7sjse/ec_service_test:stg-grpc-payment-service-stg-20250709-072323
  ports:
    containerPort: 50054
    protocol: TCP
service:
  name: grpc-payment-service
  ports:
    port: 50054
    targetPort: 50054
selector:
  app: grpc-payment-service
